/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    MySteps: typeof import('./src/components/MySteps.vue')['default']
    PinInput: typeof import('./src/components/ui/pin-input/PinInput.vue')['default']
    PinInputGroup: typeof import('./src/components/ui/pin-input/PinInputGroup.vue')['default']
    PinInputInput: typeof import('./src/components/ui/pin-input/PinInputInput.vue')['default']
    PinInputSeparator: typeof import('./src/components/ui/pin-input/PinInputSeparator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./src/components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./src/components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./src/components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./src/components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./src/components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./src/components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./src/components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./src/components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/ui/select/SelectValue.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    Stepper: typeof import('./src/components/ui/stepper/Stepper.vue')['default']
    StepperDescription: typeof import('./src/components/ui/stepper/StepperDescription.vue')['default']
    StepperIndicator: typeof import('./src/components/ui/stepper/StepperIndicator.vue')['default']
    StepperItem: typeof import('./src/components/ui/stepper/StepperItem.vue')['default']
    StepperSeparator: typeof import('./src/components/ui/stepper/StepperSeparator.vue')['default']
    StepperTitle: typeof import('./src/components/ui/stepper/StepperTitle.vue')['default']
    StepperTrigger: typeof import('./src/components/ui/stepper/StepperTrigger.vue')['default']
    Tabs: typeof import('./src/components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./src/components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./src/components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./src/components/ui/tabs/TabsTrigger.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
